spring.application.name=Job-Portal

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/jobPortal_db
spring.data.mongodb.database=jobPortal_db

#Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sakshibahirat30@gmail.com
spring.mail.password=wuirehijmiricxxw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

USER_FOUND= User has registered already.
USER_NOT_FOUND= User is not registered.
INVALID_CREDENTIALS= Invalid Credentials.
OTP_NOT_FOUND=OTP is expired.
OTP_INCORRECT=OTP is incorrect.
PROFILE_NOT_FOUND=Profile not found
JOB_NOT_FOUND= Job not found.

# JWT settings
jwt.secret=8vK2mQ9xL4sT7nP1yR6dF3hJ0cW5bN8zA2uE7gH4kL9pX1vC6mD3qS8tY5rF2jU
jwt.expiration-ms=86400000

